### ISSUE TITLE
fix whatever is wrong with Tier2S3Bucket public_bucket=true

### ISSUE THREAD

**Issue by hakamadare** [huit/nepho#52] opened 2013-09-11 19:43 UTC
from `full_monty/template.cf`:

```
{{ fleet.fleet(       name='Tier2', 
                      subnet='PrivateSubnet', 
                      elb='Tier2ElasticLoadBalancer', 
                      public_hostname='{ "Fn::GetAtt" : [ "Tier1ElasticLoadBalancer", "DNSName" ]}',
                      bucket='Tier2SharedS3Bucket',
                      public_bucket=true,
                      rds='Tier3DBInstance',
                      ports=[8080]) }}
```

causes the following error in deployment:

```
Tier2BucketPolicy CREATE_FAILED Policy element has invalid value
```

whereas:

```
{{ fleet.fleet(       name='Tier2', 
                      subnet='PrivateSubnet', 
                      elb='Tier2ElasticLoadBalancer', 
                      public_hostname='{ "Fn::GetAtt" : [ "Tier1ElasticLoadBalancer", "DNSName" ]}',
                      bucket='Tier2SharedS3Bucket',
                      public_bucket=false,
                      rds='Tier3DBInstance',
                      ports=[8080]) }}
```

appears to work fine.

**Comment by agperson** [comment] 2013-11-15 16:36
This is a cloudlet-specific issue, I'm not quite sure where to capture it, so I will just throw it into the future.

**Comment by agperson** [comment] 2013-11-15 16:39
Duplicate of #45

**Comment by agperson** [comment] 2014-01-27 15:45
For a thing that is no longer a thing.

**Closed as completed by agperson** 2014-01-27 15:45 UTC
Labels: bug
